Add forc index command to display indexer metadata (#936)
* forc index status first draft

* switch to async reqwest

to avoid:

thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.'

* basic indexer pretty-printing

* don't use slice_group_by; better print

* add a blank line between namespaces

* clippy suggestions

* forc index status authentication wip

* return indexers where pubkey matches

when no authentication, return all indexers

* add another case to indexer pretty-printing

* remove log message

* fixes